# Builder stage
# Maven image with Eclipse Temurin JDK 21 on Alpine Linux
FROM maven:3.9.12-eclipse-temurin-21-alpine AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
# Eclipse Temurin JDK 21 on Alpine Linux
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

#port
EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "app.jar" ]